# Generated by Django 3.0.10 on 2020-10-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201018_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttocourses',
            name='attendance',
            field=models.IntegerField(null=True),
        ),
    ]
