# Generated by Django 3.0.10 on 2020-10-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_discussion_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
